server:
  port: 6066
  mode: debug  # debug, release, test
  read_timeout: 60
  write_timeout: 60
  max_header_bytes: 1048576  # 1MB

database:
  driver: postgres
  host: localhost
  port: 5432
  username: <your-db-username>
  password: <your-db-password>
  dbname: llama_gin_kit
  sslmode: disable
  timezone: Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

email:
  from: "Llama Gin Kit <noreply@llamacto.com>"
  resend_api_key: "<your-resend-api-key>"

jwt:
  secret: "<your-jwt-secret>"
  expire_days: 7

openai:
  api_key: "<your-openai-api-key>"

log:
  level: debug  # debug, info, warn, error
  filename: logs/app.log
  max_size: 100    # megabytes
  max_age: 30      # days
  max_backups: 7
  compress: true

rate_limit:
  enabled: true
  requests: 100    # requests per second
  burst: 50

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization

swagger:
  enabled: true
  path: /swagger/*any

task_queue:
  redis_addr: localhost:6379
  redis_password: ""
  redis_db: 0
  concurrency: 10
  retention: 24h    # task retention period
